name: Theme Settings
description: Loads and arrange extra theme settings
type: atom
icon: fa-file-code-o

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable Theme Settings atom.
      default: true

    _info:
      type: separator.note
      class: alert alert-info
      content: <strong>TIP</strong>: Only enable following Items if you need them in your own particles or your content.

    WOWjs:
      label: Wow.js
      type: container.set
      description: Install WOW.js animations
      fields:
        .enabled:
          type: enable.enable
          label: WOW.JS Framework
          default: 1

        ._note:
          type: separator.note
          class: alert alert-info
          content: 'This Atom adds the <a href="http://mynameismatthieu.com/WOW/" target="_blank">WOW.js</a> functionality to your website.<br />WOW.js is a library to easily reveal elements as they enter the viewport (OnScroll Animations). By default, WOW.js works with <a href="https://github.com/daneden/animate.css" target="_blank">Animate.css</a> to trigger animations.'

        .offset:
          type: input.text
          label: Offset
          description: Set the distance in pixels, related to the browser bottom, to start the animation (do NOT type in 'px', enter just the digits).
          default: '100'

        .mobile:
          type: select.select
          label: Mobile
          description: Enable or disable the animations on mobile devices.
          placeholder: 'Select...'
          default: "true"
          options:
            "true": Enabled
            "false": Disabled

    uikit:
      type: container.set
      label: UI-Kit for Gantry-5
      fields:
        .enabled:
          type: enable.enable
          label: Framework
          default: 1

        _note:
          type: separator.note
          class: alert alert-info
          content: 'This Atom loads a modified and optimized version of the <a href="http://getuikit.com/index.html" target="_blank">UIkit Framework</a> prepared specifically for Gantry 5.<br />Developed and maintained by <a href="http://www.ivrenditech.com/" target="_blank">IvrendiTech.com</a><br /><br /><strong>UIkit Version:</strong><br />2.27.2<br /><br /><strong>Components Included:</strong><br />Core, Dynamic Grid, Dotnav, Progress, Slidenav, Lightbox, Slider, Slideset, Slideshow, Parallax, Accordion, Sticky, Tooltip'

        .jslocation:
          type: select.select
          label: JS Location
          description: Select where the UIkit JS assets should be loaded. The default and recommended location is 'Footer' (before the closing body tag).
          placeholder: 'Select...'
          default: footer
          options:
            footer: Footer
            head: Head


    headroomjs:
      type: container.set
      label: Headroom.js
      fields:
        .enabled:
          type: enable.enable
          label: Framework
          default: 0

        .cssselector:
          type: input.text
          description: Enter the CSS Selector for the element that should get fixed/sticky, for example '#g-header'.
          label: CSS Selector
          placeholder: '#g-header'

        .offset:
          type: input.text
          description: Enter the top offset in pixels (do NOT add 'px' at the end). This offset tells when the animation should take place.
          label: Offset
          placeholder: '300'

        .animation:
          type: select.select
          label: Animation
          description: Select the animation effect.
          placeholder: 'Select...'
          default: slide
          options:
            slide: Slide
            swing: Swing
            flip: Flip
            bounce: Bounce

        .mobile:
          type: select.select
          label: Mobile
          description: Enable or disable the fixed/sticky header on phone view.
          placeholder: 'Select...'
          default: disable
          options:
            enable: Enabled
            disable: Disabled

    cookikecontent:
      type: container.set
      label: Cookie Content
      fields:
        .enabled:
          type: enable.enable
          label: Enabled
          description: Globally enable Cookie Consent particles.
          default: true

        .messagetext:
          type: textarea.textarea
          label: Message Text
          description: Type in the message text.
          placeholder: This website uses cookies to ensure you get the best experience on our website.

        .rmtext:
          type: input.text
          label: Read More Text
          description: Type in the 'Read More' text.
          placeholder: Read more...

        .rmlink:
          type: input.text
          label: Read More Link
          description: Type in the 'Read More' URL.
          placeholder: http://example.com/policy

        .target:
          type: select.select
          label: Read More Target
          description: Target browser window when item is clicked.
          placeholder: 'Select...'
          default: _parent
          options:
              _parent: Self
              _blank: New Window

        .accepttext:
          type: input.text
          label: Accept Button Text
          description: Type in the accept button text.
          placeholder: Got it!

        .theme:
          type: select.select
          label: Theme
          description: Select the theme you wish to use.
          placeholder: 'Select...'
          default: dark-bottom
          options:
            dark-bottom: Dark Bottom
            dark-top: Dark Top
            dark-floating: Dark Floating
            dark-floating-tada: Dark Floating Tada
            dark-inline: Dark Inline
            light-bottom: Light Bottom
            light-top: Light Top
            light-floating: Light Floating

    smoothscrool:
      type: container.set
      label: SmoothScrool
      fields:
        .enabled:
          type: enable.enable
          label: Enabled
          description: Enable Smooth Scrooling on Webpages
          default: